//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabaKiralama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Musteri()
        {
            this.Tbl_Satis = new HashSet<Tbl_Satis>();
        }
    
        public int Musteri_ID { get; set; }
        public string Musteri_AdSoyad { get; set; }
        public string Musteri_TC { get; set; }
        public Nullable<System.DateTime> Musteri_DogumTarihi { get; set; }
        public string Musteri_TelNo { get; set; }
        public string Musteri_Email { get; set; }
        public Nullable<System.DateTime> Musteri_EhliyetAlmaTarihi { get; set; }
        public string Musteri_Sehir { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Satis> Tbl_Satis { get; set; }
    }
}
